---
######################### INPUT   #######################
input_folders:
  - "data/msa_trimming/asymmetric_0.5"
#  - "data/msa_trimming/asymmetric_1.0"
#  - "data/msa_trimming/asymmetric_2.0"
#  - "data/msa_trimming/symmetric_0.5"
#  - "data/msa_trimming/symmetric_1.0"
#  - "data/msa_trimming/symmetric_2.0"

######################### PARAMETERS ####################


# TODO: Write rules that run these methods accordingly
######################### SOFTWARE ######################
methods:
  filter_entropy: "bin/shannon_entropy_msa.py"
  trimAl:         "bin/trimAl/source/trimal"

distance_calculate: "bin/compare_trees.py"
FastTree:           "bin/FastTree"

