######################### INPUT   #######################
input_folders:
  - "data/data/msa_trimming/asymmetric_0.5"
  - "data/data/msa_trimming/asymmetric_1.0"
  - "data/data/msa_trimming/asymmetric_2.0"
  - "data/data/msa_trimming/symmetric_0.5"
  - "data/data/msa_trimming/symmetric_1.0"
  - "data/data/msa_trimming/symmetric_2.0"

######################### PARAMETERS ####################
thersholds:
  - 0.01
  - 0.05
  - 0.10
  - 0.2


# TODO: Write rules that run these methods accordingly
######################### SOFTWARE ######################
methods:
  - "entropy_filter"
  - "trimAI"

